### ISSUE TITLE
Fail to install by rainbond-operator as hostPath type of docker.sock is not correct

### ISSUE THREAD

**Issue by supereagle** [goodrain/rainbond#852] opened 2020-09-27 01:04 UTC
**Describe the bug**

The component `rbd-node` can not correctly start. The hostPath type of `/var/run/docker.sock` should be `Socket` instead of `File`.

```
$ kubectl -n rbd-system get po
NAME                               READY   STATUS              RESTARTS   AGE
nfs-provisioner-0                  1/1     Running             1          26h
rainbond-operator-0                2/2     Running             2          33h
rainbond-operator-sentinel-khmzs   1/1     Running             1          26h
rbd-etcd-0                         1/1     Running             1          26h
rbd-gateway-9m2vt                  1/1     Running             1          26h
rbd-hub-7db9999595-77j8x           1/1     Running             1          26h
rbd-node-8gmpd                     0/1     ContainerCreating   0          26h
$ kubectl -n rbd-system describe po rbd-node-8gmpd
Name:         rbd-node-8gmpd
Namespace:    rbd-system
Priority:     0
Node:         n227-077-210/10.227.77.210
Start Time:   Sat, 26 Sep 2020 06:55:54 +0800
Labels:       belongTo=rainbond-operator
              controller-revision-hash=7c987c86c4
              creator=Rainbond
              name=rbd-node
              pod-template-generation=1
Annotations:  <none>
Status:       Pending
IP:           10.227.77.210
IPs:
  IP:           10.227.77.210
Controlled By:  DaemonSet/rbd-node
Containers:
  rbd-node:
    Container ID:
    Image:         registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:v5.2.1-release
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --etcd=http://rbd-etcd:2379
      --hostIP=$(POD_IP)
      --run-mode master
      --noderule manage,compute
      --nodeid=$(NODE_NAME)
      --image-repo-host=goodrain.me
      --hostsfile=/newetc/hosts
      --rbd-ns=rbd-system
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Readiness:      http-get http://:6100/v2/ping delay=5s timeout=5s period=5s #success=1 #failure=3
    Environment:
      POD_IP:              (v1:status.podIP)
      NODE_NAME:           (v1:spec.nodeName)
      RBD_NAMESPACE:      rbd-system
      RBD_DOCKER_SECRET:  hub-image-repository
    Mounts:
      /etc/docker/certs.d from dockercert (rw)
      /grdata from grdata (rw)
      /newetc from etc (rw)
      /sys from sys (rw)
      /var/docker/lib from vardocker (rw)
      /var/lib/docker from docker (rw)
      /var/run/docker.sock from dockersock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rainbond-operator-token-2qnkz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  grdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  rbd-cpt-grdata
    ReadOnly:   false
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  Directory
  docker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  DirectoryOrCreate
  vardocker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/docker/lib
    HostPathType:  DirectoryOrCreate
  dockercert:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/docker/certs.d
    HostPathType:  DirectoryOrCreate
  dockersock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  File
  etc:
    Type:          HostPath (bare host directory volume)
    Path:          /etc
    HostPathType:  Directory
  rainbond-operator-token-2qnkz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rainbond-operator-token-2qnkz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  50m (x37 over 9h)     kubelet  Unable to attach or mount volumes: unmounted volumes=[dockersock], unattached volumes=[docker vardocker dockercert etc rainbond-operator-token-2qnkz grdata sys dockersock]: timed out waiting for the condition
  Warning  FailedMount  45m (x32 over 7h56m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[dockersock], unattached volumes=[dockersock docker vardocker dockercert etc rainbond-operator-token-2qnkz grdata sys]: timed out waiting for the condition
  Warning  FailedMount  10m (x286 over 9h)    kubelet  MountVolume.SetUp failed for volume "dockersock" : hostPath type check failed: /var/run/docker.sock is not a file
  Warning  FailedMount  5m10s (x39 over 9h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[dockersock], unattached volumes=[vardocker dockercert etc rainbond-operator-token-2qnkz grdata sys dockersock docker]: timed out waiting for the condition
  Warning  FailedMount  35s (x25 over 9h)     kubelet  Unable to attach or mount volumes: unmounted volumes=[dockersock], unattached volumes=[sys dockersock docker vardocker dockercert etc rainbond-operator-token-2qnkz grdata]: timed out waiting for the condition
```

**To Reproduce**
1. Install rainbond-operator v1.1
2. Install rainbond by rainbond-operator

**Screenshots**

![image](https://user-images.githubusercontent.com/3390333/94353168-4c4fd600-00a0-11eb-94f8-d9f3dc61b07b.png)

**The relevant information:**
 - Rainbond Version: v5.2.1
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version: v1.19.2

**Comment by barnettZQG** [comment] 2020-09-27 03:12
@GLYASAI 
The `HostPathType` should not be the root cause of the issues.  `/var/run/docker.sock` it exist?

**Comment by GLYASAI** [comment] 2020-09-27 03:37
请问这个环境的 docker 版本是多少，通过什么方式安装的？

默认挂载 docker.sock 的 HostPathType 是 File，用以下的命令把 HostPathType 置空试试。
```
cat  << EOF | kubectl apply -f -
apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-node
    priorityComponent: "true"
  name: rbd-node
  namespace: rbd-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:v5.2.1-release
  imagePullPolicy: IfNotPresent
  priorityComponent: true
  replicas: 1
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: dockersock
EOF
```

**Comment by supereagle** [comment] 2020-09-27 12:47
> `/var/run/docker.sock` it exist?

`docker.sock` does exist.

```
$ ls -al /var/run/docker.sock
srw-rw---- 1 root docker 0 Sep 26 23:19 /var/run/docker.sock
```

**Comment by supereagle** [comment] 2020-09-27 12:50
@GLYASAI  Your method works, `rbd-node` is running after run this command.

**Comment by supereagle** [comment] 2020-09-27 15:52
The installation is ok for Kubernetes v1.18.6, and the hostPath type is `Socket`. Maybe it is caused by the different Kubernetes version.

`rbd-node` on k8s v1.18.6:
```
# kubectl -n rbd-system describe po rbd-node-9tqlq
Name:         rbd-node-9tqlq
Namespace:    rbd-system
Priority:     0
Node:         wd-1v33-53/192.168.33.53
Start Time:   Sun, 27 Sep 2020 23:41:19 +0800
Labels:       belongTo=rainbond-operator
              controller-revision-hash=7dd5cb6c86
              creator=Rainbond
              name=rbd-node
              pod-template-generation=1
Annotations:  <none>
Status:       Running
IP:           192.168.33.53
IPs:
  IP:           192.168.33.53
Controlled By:  DaemonSet/rbd-node
Containers:
  rbd-node:
    Container ID:  docker://c9d4c20f94ff8c537aada88d7d718778ca33a9dda15b56012c5ebc2eceb43e38
    Image:         registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:v5.2.1-release
    Image ID:      docker-pullable://registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node@sha256:3c9669004aff1bddd2d84d9a9a06fb9858f61ebe934fb28c42c257608944de77
    Port:          <none>
    Host Port:     <none>
    Args:
      --etcd=http://rbd-etcd:2379
      --hostIP=$(POD_IP)
      --run-mode master
      --noderule manage,compute
      --nodeid=$(NODE_NAME)
      --image-repo-host=cargo.dev.caicloud.xyz/test
      --hostsfile=/newetc/hosts
      --rbd-ns=rbd-system
    State:          Running
      Started:      Sun, 27 Sep 2020 23:41:41 +0800
    Ready:          True
    Restart Count:  0
    Readiness:      http-get http://:6100/v2/ping delay=5s timeout=5s period=5s #success=1 #failure=3
    Environment:
      POD_IP:          (v1:status.podIP)
      NODE_NAME:       (v1:spec.nodeName)
      RBD_NAMESPACE:  rbd-system
    Mounts:
      /etc/docker/certs.d from dockercert (rw)
      /grdata from grdata (rw)
      /newetc from etc (rw)
      /sys from sys (rw)
      /var/docker/lib from vardocker (rw)
      /var/lib/docker from docker (rw)
      /var/run/docker.sock from dockersock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rainbond-operator-token-mzc8g (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  grdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  rbd-cpt-grdata
    ReadOnly:   false
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  Directory
  docker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  DirectoryOrCreate
  vardocker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/docker/lib
    HostPathType:  DirectoryOrCreate
  dockercert:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/docker/certs.d
    HostPathType:  DirectoryOrCreate
  dockersock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
  etc:
    Type:          HostPath (bare host directory volume)
    Path:          /etc
    HostPathType:  Directory
  rainbond-operator-token-mzc8g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rainbond-operator-token-mzc8g
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                     From                 Message
  ----     ------     ----                    ----                 -------
  Normal   Scheduled  5m10s                   default-scheduler    Successfully assigned rbd-system/rbd-node-9tqlq to wd-1v33-53
  Normal   Pulling    5m9s                    kubelet, wd-1v33-53  Pulling image "registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:v5.2.1-release"
  Normal   Pulled     4m48s                   kubelet, wd-1v33-53  Successfully pulled image "registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:v5.2.1-release"
  Normal   Created    4m48s                   kubelet, wd-1v33-53  Created container rbd-node
  Normal   Started    4m48s                   kubelet, wd-1v33-53  Started container rbd-node
  Warning  Unhealthy  3m22s (x17 over 4m42s)  kubelet, wd-1v33-53  Readiness probe failed: Get http://192.168.33.53:6100/v2/ping: dial tcp 192.168.33.53:6100: connect: connection refused
```

**Comment by GLYASAI** [comment] 2020-09-28 01:23
rbd-node health check fails, please provide the log of rbd-node:

```bash
kubectl logs -f -l name=rbd-node -n rbd-system
```

**Comment by barnettZQG** [comment] 2020-09-28 01:26
@GLYASAI    `Ready: True`，maybe socket file mount must set HostPathType is `Socket`.  We need to confirm the mechanism of Kubernetes.

**Comment by GLYASAI** [comment] 2020-09-28 01:41
OK. The latest registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator:v1.1.0 image has changed the HostPathType to Socket.

**Comment by barnettZQG** [comment] 2020-09-29 10:44
Close this issue. Please reopen it if you still have any questions.

**Closed by barnettZQG** 2020-09-29 10:44 UTC
Labels: BUG Feedback
