### ISSUE TITLE
Fail to bind custom domain name

### ISSUE THREAD

**Issue by mchtech** [goodrain/rainbond#66] opened 2018-04-13 15:20 UTC
> bug

**Description**

In "port configuration" page:

1. generate "wrong" nginx configuration in "rbd-lb". 
(1)  If the domain name is "a.somedomain.tld", the "server_name" section of generated config files: "a.somedomain.tld..conf" and "a.somedomain.tld._upstream.conf" will be its FQDN: "a.somedomain.tld."(with a suffix '.'). It seems that FQDN is not recogonized as a valid hostname in nginx, which leads to displaying the "app is preparing" page. After I login to "rbd-lb" , remove the suffix '.' of "server_name" section in the config files and reload nginx, the app could be visited by custom domain name(hostname).
(2) If the domain name is "a-b.somedomain.tld",the "server_name" section of config files will be "a_b.somedomain.tld."('-' is replaced by '_'). It also leads to same problem in 1.(1).

2. It seems that https configuration is not available, as there is not relative config section on https config and nginx is not bind and listen to TCP port 443.

**Environment**:
rainbond version:3.5
Cloud provider or hardware configuration:qemu-kvm
OS (e.g. from /etc/os-release):centos 7.4
Kernel (e.g. uname -a):3.10.0-693.21.1.el7.x86_64
docker image version:1.12.6
grctl version:0.0.0
Others:

**Comment by barnettZQG** [comment] 2018-04-13 15:45
@mchtech opensource version 3.5 do not support https and custom domain.  next version could support.

**Comment by sycki** [comment] 2018-04-24 09:04
The issue is fixed in 3.6 version, please specify option `--plugin-name=openresty` for start entrance.

**Closed by sycki** 2018-04-24 09:04 UTC
